
SELECT 
	*
FROM
	PortfolioProject..CovidVaccinations
WHERE
	CONTINENT IS NOT NULL
ORDER BY
	3,4

--SELECT 
--	*
--FROM
--	PortfolioProject..CovidDeaths
--ORDER BY
--	3,4

SELECT
	LOCATION,DATE,TOTAL_CASES,NEW_CASES,TOTAL_DEATHS,POPULATION
FROM
	PortfolioProject..CovidDeaths
WHERE
	CONTINENT IS NOT NULL
ORDER BY
	1,2;

--OVERLOOK THE RELATIONSHIP BETWEEN CASES AND DEATHS

SELECT
	LOCATION,DATE,TOTAL_CASES,NEW_CASES,TOTAL_DEATHS,(CAST (TOTAL_DEATHS AS FLOAT)/CAST (TOTAL_CASES AS FLOAT))*100 as DeathPercentage
FROM
	PortfolioProject..CovidDeaths
WHERE
	LOCATION LIKE '%Malay%%' AND
	CONTINENT IS NOT NULL
ORDER BY
	1,2;

--OVERLOOK THE RELATIONSHIP BETWEEN CASES AND POPULATION

SELECT
	LOCATION,DATE,POPULATION,TOTAL_CASES,NEW_CASES,TOTAL_DEATHS,(CAST (TOTAL_CASES AS FLOAT)/CAST (POPULATION AS FLOAT))*100 as InfectionPercentage
FROM
	PortfolioProject..CovidDeaths
WHERE
	LOCATION LIKE '%Malay%%' AND
	CONTINENT IS NOT NULL
ORDER BY
	1,2; 

--FIND HIGHEST INFECTION RATE COUNTRY

SELECT
	LOCATION,POPULATION,MAX(total_case) AS HighestInfectionCount,MAX((total_case/population))*100 AS PercentagePeopleInfected
FROM
	PortfolioProject..CovidDeaths 
WHERE
	CONTINENT IS NOT NULL
GROUP BY
	LOCATION,POPULATION
ORDER BY
	PercentagePeopleInfected DESC


--SHOWING COUNTRIES WITH HIGHEST DEATH COUNTH PER POPULATION
--total death is the casted column from total_deaths

SELECT
	LOCATION,MAX(total_death) AS TotalDeathCount
FROM
	PortfolioProject..CovidDeaths 
WHERE
	CONTINENT IS NOT NULL
GROUP BY
	LOCATION
ORDER BY
	TotalDeathCount DESC

-- LETS VIEW FROM CONTINENT PERSPECTIVE

SELECT
	LOCATION,MAX(total_death) AS TotalDeathCount
FROM
	PortfolioProject..CovidDeaths 
WHERE
	CONTINENT IS NULL
GROUP BY
	location
ORDER BY
	TotalDeathCount DESC

--SHOWING CONTINENT WITH HIGHEST DEATH COUNT/POPULATION
SELECT
	CONTINENT,MAX(total_death) AS TotalDeathCount
FROM
	PortfolioProject..CovidDeaths 
WHERE
	CONTINENT IS NOT NULL
GROUP BY
	CONTINENT
ORDER BY
	TotalDeathCount DESC

-- GLOBAL NUMBERS
SELECT
	DATE,SUM(NEW_CASES) AS TOTAL_CASES,
	SUM(CAST(NEW_DEATHS AS INT)) AS TOTAL_DEATHS
	

FROM
	PortfolioProject..CovidDeaths 
WHERE 
	new_cases IS NOT NULL AND
	new_deaths IS NOT NULL 

GROUP BY
	DATE
ORDER BY
	1,2
	
-- OVERVIEW ON RELATIONSHIP BETWEEN TOTAL VACCINATION AND POPULATION
SELECT
	DEA.continent,DEA.LOCATION,DEA.DATE,DEA.POPULATION,VAC.new_vaccinations,
	SUM(CONVERT(INT,VAC.new_vaccinations)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION,DEA.DATE) AS Accu_Vaccinated
FROM
	PortfolioProject..CovidDeaths Dea
JOIN PortfolioProject..CovidVaccinations Vac
	ON DEA.LOCATION = VAC.location AND
	DEA.DATE = VAC.DATE
WHERE 
	DEA.continent IS NOT NULL
ORDER BY 2,3

--Tring CTE
With PopvsVac (Continent,Location,Date,Population,New_Vaccination,Accu_Vacc)
as
(
SELECT
	DEA.continent,DEA.LOCATION,DEA.DATE,DEA.POPULATION,VAC.new_vaccinations,
	SUM(CONVERT(INT,VAC.new_vaccinations)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION,DEA.DATE) AS Accu_Vacc
FROM
	PortfolioProject..CovidDeaths Dea
JOIN PortfolioProject..CovidVaccinations Vac
	ON DEA.LOCATION = VAC.location AND
	DEA.DATE = VAC.DATE
WHERE 
	DEA.continent IS NOT NULL
)

SELECT
	*,(Accu_Vacc/Population) * 100 AS PERCENTAGE
FROM
	PopvsVac

--TEMP TABLE
DROP TABLE IF EXISTS #PERCENTPOPULATIONVACCINATED
CREATE TABLE #PERCENTPOPULATIONVACCINATED
(
Continent nvarchar(255),
Location nvarchar(255),
Date datetime,
Population numeric,
New_Vaccination numeric,
Accu_Vacc numeric
)

INSERT INTO #PERCENTPOPULATIONVACCINATED
SELECT
	DEA.continent,DEA.LOCATION,DEA.DATE,DEA.POPULATION,VAC.new_vaccinations,
	SUM(CAST(VAC.new_vaccinations AS BIGINT)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION,DEA.DATE) AS Accu_Vaccinated
FROM
	PortfolioProject..CovidDeaths Dea
JOIN PortfolioProject..CovidVaccinations Vac
	ON DEA.LOCATION = VAC.location AND
	DEA.DATE = VAC.DATE
WHERE 
	DEA.continent IS NOT NULL


--CHECK TEMP TABLE
SELECT 
	*
FROM
	#PERCENTPOPULATIONVACCINATED

--CREATE VIEW TO STORE DATA FOR VIZ
CREATE VIEW PERCENTPOPULATIONVACC AS
SELECT
	DEA.continent,DEA.LOCATION,DEA.DATE,DEA.POPULATION,VAC.new_vaccinations,
	SUM(CAST(VAC.new_vaccinations AS BIGINT)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION,DEA.DATE) AS Accu_Vaccinated
FROM
	PortfolioProject..CovidDeaths Dea
JOIN PortfolioProject..CovidVaccinations Vac
	ON DEA.LOCATION = VAC.location AND
	DEA.DATE = VAC.DATE
WHERE 
	DEA.continent IS NOT NULL

--CHECK VIEW
SELECT * FROM PERCENTPOPULATIONVACC
